export type Card = {
    id: number;
    src: string;
    isFlipped: boolean,
    isMatched: boolean,
};

export const codeCards: Card[] = [
    { id: 1, src: "./src/assets/fonts/images/card_img/angularIcon.png", isFlipped: false, isMatched:false },
    { id: 1, src: "./src/assets/fonts/images/card_img/angularIcon.png", isFlipped: false, isMatched:false },
    { id: 2, src: "./src/assets/fonts/images/card_img/bootstrap.png", isFlipped: false, isMatched:false },
    { id: 2, src: "./src/assets/fonts/images/card_img/bootstrap.png", isFlipped: false, isMatched:false },
    { id: 3, src: "./src/assets/fonts/images/card_img/cssLogo.png", isFlipped: false, isMatched:false },
    { id: 3, src: "./src/assets/fonts/images/card_img/cssLogo.png", isFlipped: false, isMatched:false },
    { id: 4, src: "./src/assets/fonts/images/card_img/djangoIcon.png", isFlipped: false, isMatched:false },
    { id: 4, src: "./src/assets/fonts/images/card_img/djangoIcon.png", isFlipped: false, isMatched:false },
    { id: 5, src: "./src/assets/fonts/images/card_img/firebaseIcon.png", isFlipped: false, isMatched:false },
    { id: 5, src: "./src/assets/fonts/images/card_img/firebaseIcon.png", isFlipped: false, isMatched:false },
    { id: 6, src: "./src/assets/fonts/images/card_img/githubIcon.png", isFlipped: false, isMatched:false },
    { id: 6, src: "./src/assets/fonts/images/card_img/githubIcon.png", isFlipped: false, isMatched:false },
    { id: 7, src: "./src/assets/fonts/images/card_img/gitIcon.png", isFlipped: false, isMatched:false },
    { id: 7, src: "./src/assets/fonts/images/card_img/gitIcon.png", isFlipped: false, isMatched:false },
    { id: 8, src: "./src/assets/fonts/images/card_img/htmlIcon.png", isFlipped: false, isMatched:false },
    { id: 8, src: "./src/assets/fonts/images/card_img/htmlIcon.png", isFlipped: false, isMatched:false },
    { id: 9, src: "./src/assets/fonts/images/card_img/JsIcon.png", isFlipped: false, isMatched:false },
    { id: 9, src: "./src/assets/fonts/images/card_img/JsIcon.png", isFlipped: false, isMatched:false },
    { id: 10, src: "./src/assets/fonts/images/card_img/nodejsIcon.png", isFlipped: false, isMatched:false },
    { id: 10, src: "./src/assets/fonts/images/card_img/nodejsIcon.png", isFlipped: false, isMatched:false },
    { id: 11, src: "./src/assets/fonts/images/card_img/pythonIcon.png", isFlipped: false, isMatched:false },
    { id: 11, src: "./src/assets/fonts/images/card_img/pythonIcon.png", isFlipped: false, isMatched:false },
    { id: 12, src: "./src/assets/fonts/images/card_img/reactIcon.png", isFlipped: false, isMatched:false },
    { id: 12, src: "./src/assets/fonts/images/card_img/reactIcon.png", isFlipped: false, isMatched:false },
    { id: 13, src: "./src/assets/fonts/images/card_img/SassIcon.png", isFlipped: false, isMatched:false },
    { id: 13, src: "./src/assets/fonts/images/card_img/SassIcon.png", isFlipped: false, isMatched:false },
    { id: 14, src: "./src/assets/fonts/images/card_img/SQL.png", isFlipped: false, isMatched:false },
    { id: 14, src: "./src/assets/fonts/images/card_img/SQL.png", isFlipped: false, isMatched:false },
    { id: 15, src: "./src/assets/fonts/images/card_img/terminalIcon.png", isFlipped: false, isMatched:false },
    { id: 15, src: "./src/assets/fonts/images/card_img/terminalIcon.png", isFlipped: false, isMatched:false },
    { id: 16, src: "./src/assets/fonts/images/card_img/typescriptIcon.png", isFlipped: false, isMatched:false },
    { id: 16, src: "./src/assets/fonts/images/card_img/typescriptIcon.png", isFlipped: false, isMatched:false },
    { id: 17, src: "./src/assets/fonts/images/card_img/VSCodeIcon.png", isFlipped: false, isMatched:false },
    { id: 17, src: "./src/assets/fonts/images/card_img/VSCodeIcon.png", isFlipped: false, isMatched:false },
    { id: 18, src: "./src/assets/fonts/images/card_img/vueJS.png", isFlipped: false, isMatched:false },
    { id: 18, src: "./src/assets/fonts/images/card_img/vueJS.png", isFlipped: false, isMatched:false }
];

export const gamingCards: Card[] = [
    { id: 1, src: "./src/assets/fonts/images/card_gaming_img/bananaGaming.png", isFlipped: false, isMatched:false },
    { id: 1, src: "./src/assets/fonts/images/card_gaming_img/bananaGaming.png", isFlipped: false, isMatched:false },
    { id: 2, src: "./src/assets/fonts/images/card_gaming_img/bigPacmanGaming.png", isFlipped: false, isMatched:false },
    { id: 2, src: "./src/assets/fonts/images/card_gaming_img/bigPacmanGaming.png", isFlipped: false, isMatched:false },
    { id: 3, src: "./src/assets/fonts/images/card_gaming_img/cardGaming.png", isFlipped: false, isMatched:false },
    { id: 3, src: "./src/assets/fonts/images/card_gaming_img/cardGaming.png", isFlipped: false, isMatched:false },
    { id: 4, src: "./src/assets/fonts/images/card_gaming_img/circleGaming.png", isFlipped: false, isMatched:false },
    { id: 4, src: "./src/assets/fonts/images/card_gaming_img/circleGaming.png", isFlipped: false, isMatched:false },
    { id: 5, src: "./src/assets/fonts/images/card_gaming_img/coinGaming.png", isFlipped: false, isMatched:false },
    { id: 5, src: "./src/assets/fonts/images/card_gaming_img/coinGaming.png", isFlipped: false, isMatched:false },
    { id: 6, src: "./src/assets/fonts/images/card_gaming_img/creeperGaming.png", isFlipped: false, isMatched:false },
    { id: 6, src: "./src/assets/fonts/images/card_gaming_img/creeperGaming.png", isFlipped: false, isMatched:false },
    { id: 7, src: "./src/assets/fonts/images/card_gaming_img/cubeGaming.png", isFlipped: false, isMatched:false },
    { id: 7, src: "./src/assets/fonts/images/card_gaming_img/cubeGaming.png", isFlipped: false, isMatched:false },
    { id: 8, src: "./src/assets/fonts/images/card_gaming_img/gameboyGaming.png", isFlipped: false, isMatched:false },
    { id: 8, src: "./src/assets/fonts/images/card_gaming_img/gameboyGaming.png", isFlipped: false, isMatched:false },
    { id: 9, src: "./src/assets/fonts/images/card_gaming_img/levelGaming.png", isFlipped: false, isMatched:false },
    { id: 9, src: "./src/assets/fonts/images/card_gaming_img/levelGaming.png", isFlipped: false, isMatched:false },
    { id: 10, src: "./src/assets/fonts/images/card_gaming_img/mushroomGaming.png", isFlipped: false, isMatched:false },
    { id: 10, src: "./src/assets/fonts/images/card_gaming_img/mushroomGaming.png", isFlipped: false, isMatched:false },
    { id: 11, src: "./src/assets/fonts/images/card_gaming_img/pacmanGaming.png", isFlipped: false, isMatched:false },
    { id: 11, src: "./src/assets/fonts/images/card_gaming_img/pacmanGaming.png", isFlipped: false, isMatched:false },
    { id: 12, src: "./src/assets/fonts/images/card_gaming_img/playerGaming.png", isFlipped: false, isMatched:false },
    { id: 12, src: "./src/assets/fonts/images/card_gaming_img/playerGaming.png", isFlipped: false, isMatched:false },
    { id: 13, src: "./src/assets/fonts/images/card_gaming_img/playGaming.png", isFlipped: false, isMatched:false },
    { id: 13, src: "./src/assets/fonts/images/card_gaming_img/playGaming.png", isFlipped: false, isMatched:false },
    { id: 14, src: "./src/assets/fonts/images/card_gaming_img/puzzleGaming.png", isFlipped: false, isMatched:false },
    { id: 14, src: "./src/assets/fonts/images/card_gaming_img/puzzleGaming.png", isFlipped: false, isMatched:false },
    { id: 15, src: "./src/assets/fonts/images/card_gaming_img/quarterGaming.png", isFlipped: false, isMatched:false },
    { id: 15, src: "./src/assets/fonts/images/card_gaming_img/quarterGaming.png", isFlipped: false, isMatched:false },
    { id: 16, src: "./src/assets/fonts/images/card_gaming_img/runesGaming.png", isFlipped: false, isMatched:false },
    { id: 16, src: "./src/assets/fonts/images/card_gaming_img/runesGaming.png", isFlipped: false, isMatched:false },
    { id: 17, src: "./src/assets/fonts/images/card_gaming_img/snakeGaming.png", isFlipped: false, isMatched:false },
    { id: 17, src: "./src/assets/fonts/images/card_gaming_img/snakeGaming.png", isFlipped: false, isMatched:false },
    { id: 18, src: "./src/assets/fonts/images/card_gaming_img/traiangleGaming.png", isFlipped: false, isMatched:false },
    { id: 18, src: "./src/assets/fonts/images/card_gaming_img/traiangleGaming.png", isFlipped: false, isMatched:false }
];
